-- Create database
CREATE DATABASE IF NOT EXISTS RAMAGALLERY_DB 
CHARACTER SET utf8mb4 
COLLATE utf8mb4_unicode_ci;

USE RAMAGALLERY_DB;

-- Users table (relates to system users)
CREATE TABLE IF NOT EXISTS CHAT_USERS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    USER_UUID VARCHAR(36) NOT NULL UNIQUE,
    USER_ID INT,
    USERNAME VARCHAR(100),
    EMAIL VARCHAR(255),
    VISITOR_ID VARCHAR(255),
    IP_ADDRESS VARCHAR(45),
    USER_AGENT TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    LAST_ACTIVE TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID) ON DELETE CASCADE,
    INDEX IDX_USER_UUID (USER_UUID),
    INDEX IDX_VISITOR_ID (VISITOR_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Chat sessions table
CREATE TABLE IF NOT EXISTS CHAT_SESSIONS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    SESSION_UUID VARCHAR(36) NOT NULL UNIQUE,
    USER_ID INT,
    START_TIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    END_TIME TIMESTAMP NULL,
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    TOTAL_MESSAGES INT DEFAULT 0,
    FOREIGN KEY (USER_ID) REFERENCES CHAT_USERS(ID) ON DELETE CASCADE,
    INDEX IDX_SESSION_UUID (SESSION_UUID),
    INDEX IDX_USER_ID (USER_ID),
    INDEX IDX_IS_ACTIVE (IS_ACTIVE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Messages table
CREATE TABLE IF NOT EXISTS CHAT_MESSAGES (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    MESSAGE_UUID VARCHAR(36) NOT NULL UNIQUE,
    SESSION_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    ROLE ENUM('USER', 'ASSISTANT', 'SYSTEM') NOT NULL,
    CONTENT TEXT NOT NULL,
    LANGUAGE_DETECTED VARCHAR(5),
    TOKENS_USED INT DEFAULT 0,
    MODEL_USED VARCHAR(100),
    RESPONSE_TIME_MS INT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    IS_EDITED BOOLEAN DEFAULT FALSE,
    PARENT_MESSAGE_ID INT NULL,
    FOREIGN KEY (SESSION_ID) REFERENCES CHAT_SESSIONS(ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES CHAT_USERS(ID) ON DELETE CASCADE,
    FOREIGN KEY (PARENT_MESSAGE_ID) REFERENCES CHAT_MESSAGES(ID) ON DELETE SET NULL,
    INDEX IDX_SESSION_ID (SESSION_ID),
    INDEX IDX_USER_ID (USER_ID),
    INDEX IDX_CREATED_AT (CREATED_AT),
    INDEX IDX_ROLE (ROLE)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Documents table for AI knowledge base
CREATE TABLE IF NOT EXISTS AI_DOCUMENTS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    DOCUMENT_UUID VARCHAR(36) NOT NULL UNIQUE,
    TITLE VARCHAR(500) NOT NULL,
    CONTENT LONGTEXT NOT NULL,
    DOCUMENT_TYPE VARCHAR(50),
    CATEGORY VARCHAR(100),
    TAGS JSON,
    LANGUAGE VARCHAR(5) DEFAULT 'EN',
    IS_ACTIVE BOOLEAN DEFAULT TRUE,
    VERSION INT DEFAULT 1,
    METADATA JSON,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    INDEX IDX_TITLE (TITLE(255)),
    INDEX IDX_CATEGORY (CATEGORY),
    INDEX IDX_IS_ACTIVE (IS_ACTIVE),
    FULLTEXT INDEX FTX_CONTENT (CONTENT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Document chunks for better retrieval
CREATE TABLE IF NOT EXISTS AI_DOCUMENT_CHUNKS (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CHUNK_UUID VARCHAR(36) NOT NULL UNIQUE,
    DOCUMENT_ID INT NOT NULL,
    CHUNK_INDEX INT NOT NULL,
    CONTENT TEXT NOT NULL,
    EMBEDDING JSON NULL,
    FOREIGN KEY (DOCUMENT_ID) REFERENCES AI_DOCUMENTS(ID) ON DELETE CASCADE,
    INDEX IDX_DOCUMENT_ID (DOCUMENT_ID),
    INDEX IDX_CHUNK_INDEX (CHUNK_INDEX),
    FULLTEXT INDEX FTX_CHUNK_CONTENT (CONTENT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- User feedback on AI responses
CREATE TABLE IF NOT EXISTS CHAT_FEEDBACK (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    MESSAGE_ID INT NOT NULL,
    USER_ID INT NOT NULL,
    FEEDBACK_TYPE ENUM('LIKE', 'DISLIKE', 'HELPFUL', 'NOT_HELPFUL') NOT NULL,
    COMMENT TEXT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (MESSAGE_ID) REFERENCES CHAT_MESSAGES(ID) ON DELETE CASCADE,
    FOREIGN KEY (USER_ID) REFERENCES CHAT_USERS(ID) ON DELETE CASCADE,
    UNIQUE KEY UNIQ_USER_MESSAGE (MESSAGE_ID, USER_ID),
    INDEX IDX_MESSAGE_ID (MESSAGE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Art gallery specific content
CREATE TABLE IF NOT EXISTS GALLERY_CONTENT (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    CONTENT_UUID VARCHAR(36) NOT NULL UNIQUE,
    TYPE ENUM('ARTWORK', 'BLOG', 'EXHIBITION', 'EVENT') NOT NULL,
    TITLE VARCHAR(500) NOT NULL,
    DESCRIPTION TEXT,
    CONTENT LONGTEXT,
    METADATA JSON,
    VIEW_COUNT INT DEFAULT 0,
    LIKE_COUNT INT DEFAULT 0,
    SHARE_COUNT INT DEFAULT 0,
    COMMENT_COUNT INT DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FULLTEXT INDEX FTX_TITLE_DESC (TITLE, DESCRIPTION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;



CREATE TABLE KNOWLEDGE_DOCUMENTS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,

    TITLE VARCHAR(255) NOT NULL,

    SLUG VARCHAR(255) UNIQUE,

    CONTENT LONGTEXT NOT NULL,

    CATEGORY VARCHAR(100),

    TAGS JSON,

    LANGUAGE VARCHAR(10) DEFAULT 'en',

    IS_ACTIVE BOOLEAN DEFAULT TRUE,

    PRIORITY INT DEFAULT 0,

    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP
);
Add FULLTEXT Index
migration SQL
ALTER TABLE KNOWLEDGE_DOCUMENTS
ADD FULLTEXT(title, content);

CREATE TABLE CHAT_LOGS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,

    SESSION_ID VARCHAR(120),

    QUESTION TEXT,

    ANSWER LONGTEXT,

    MODEL VARCHAR(120),

    TOKENS_USED INT,

    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);