-- ============================================================
-- INVENTORY, SALES & LOGISTICS DATABASE
-- MySQL 8.0+ | UTF8MB4 | InnoDB | 3NF Normalized
-- All Tables and Fields in UPPERCASE
-- ============================================================

DROP DATABASE IF EXISTS INVENTORY_LOGISTICS_DB;
CREATE DATABASE INVENTORY_LOGISTICS_DB CHARACTER SET UTF8MB4 COLLATE UTF8MB4_UNICODE_CI;
USE INVENTORY_LOGISTICS_DB;

-- ============================================================
-- 1. REFERENCE / LOOKUP TABLES
-- ============================================================

CREATE TABLE ADDRESS (
    ADDRESS_ID          BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ADDRESS_LINE1       VARCHAR(200) NOT NULL,
    ADDRESS_LINE2       VARCHAR(200),
    CITY                VARCHAR(100) NOT NULL,
    STATE_PROVINCE      VARCHAR(100) NOT NULL,
    POSTAL_CODE         VARCHAR(20) NOT NULL,
    COUNTRY_CODE        CHAR(2) NOT NULL DEFAULT 'US',
    LATITUDE            DECIMAL(10, 8),
    LONGITUDE           DECIMAL(11, 8),
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    INDEX IDX_ADDRESS_CITY (CITY),
    INDEX IDX_ADDRESS_COUNTRY (COUNTRY_CODE),
    INDEX IDX_ADDRESS_POSTAL (POSTAL_CODE)
) ENGINE=INNODB;

CREATE TABLE CARRIER (
    CARRIER_ID          BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    CARRIER_NAME        VARCHAR(100) NOT NULL,
    CARRIER_CODE        VARCHAR(50) NOT NULL UNIQUE,
    SERVICE_TYPE        VARCHAR(50),
    CONTACT_PHONE       VARCHAR(20),
    IS_ACTIVE           BOOLEAN DEFAULT TRUE,

    INDEX IDX_CARRIER_CODE (CARRIER_CODE),
    INDEX IDX_CARRIER_ACTIVE (IS_ACTIVE)
) ENGINE=INNODB;

CREATE TABLE USER (
    USER_ID             BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    USERNAME            VARCHAR(50) NOT NULL UNIQUE,
    EMAIL               VARCHAR(100) NOT NULL UNIQUE,
    FIRST_NAME          VARCHAR(50) NOT NULL,
    LAST_NAME           VARCHAR(50) NOT NULL,
    ROLE                ENUM('ADMIN', 'MANAGER', 'WAREHOUSE_STAFF', 'SALES_REP', 'PURCHASER', 'LOGISTICS_COORDINATOR') NOT NULL DEFAULT 'WAREHOUSE_STAFF',
    WAREHOUSE_ID        BIGINT UNSIGNED,
    IS_ACTIVE           BOOLEAN DEFAULT TRUE,
    LAST_LOGIN          TIMESTAMP NULL,
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    INDEX IDX_USER_USERNAME (USERNAME),
    INDEX IDX_USER_ROLE (ROLE),
    INDEX IDX_USER_WAREHOUSE (WAREHOUSE_ID)
) ENGINE=INNODB;

-- ============================================================
-- 2. MASTER DATA TABLES
-- ============================================================

CREATE TABLE CATEGORY (
    CATEGORY_ID         BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    CATEGORY_NAME       VARCHAR(100) NOT NULL,
    PARENT_CATEGORY_ID  BIGINT UNSIGNED,
    DESCRIPTION         VARCHAR(500),
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (PARENT_CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID) ON DELETE SET NULL,
    INDEX IDX_CATEGORY_NAME (CATEGORY_NAME),
    INDEX IDX_CATEGORY_PARENT (PARENT_CATEGORY_ID)
) ENGINE=INNODB;

CREATE TABLE SUPPLIER (
    SUPPLIER_ID         BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    SUPPLIER_CODE       VARCHAR(50) NOT NULL UNIQUE,
    SUPPLIER_NAME       VARCHAR(200) NOT NULL,
    CONTACT_NAME        VARCHAR(100),
    EMAIL               VARCHAR(100),
    PHONE               VARCHAR(20),
    ADDRESS_ID          BIGINT UNSIGNED,
    PAYMENT_TERMS       VARCHAR(50),
    IS_ACTIVE           BOOLEAN DEFAULT TRUE,
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID) ON DELETE SET NULL,
    INDEX IDX_SUPPLIER_CODE (SUPPLIER_CODE),
    INDEX IDX_SUPPLIER_ACTIVE (IS_ACTIVE)
) ENGINE=INNODB;

CREATE TABLE PRODUCT (
    PRODUCT_ID          BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    SKU                 VARCHAR(50) NOT NULL UNIQUE,
    PRODUCT_NAME        VARCHAR(200) NOT NULL,
    DESCRIPTION         TEXT,
    CATEGORY_ID         BIGINT UNSIGNED,
    SUPPLIER_ID         BIGINT UNSIGNED,
    UNIT_PRICE          DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    UNIT_COST           DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    IS_ACTIVE           BOOLEAN DEFAULT TRUE,
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY(CATEGORY_ID) ON DELETE SET NULL,
    FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER(SUPPLIER_ID) ON DELETE SET NULL,
    INDEX IDX_PRODUCT_SKU (SKU),
    INDEX IDX_PRODUCT_CATEGORY (CATEGORY_ID),
    INDEX IDX_PRODUCT_SUPPLIER (SUPPLIER_ID),
    INDEX IDX_PRODUCT_ACTIVE (IS_ACTIVE)
) ENGINE=INNODB;

CREATE TABLE CUSTOMER (
    CUSTOMER_ID         BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_CODE       VARCHAR(50) NOT NULL UNIQUE,
    CUSTOMER_NAME       VARCHAR(200) NOT NULL,
    CUSTOMER_TYPE       ENUM('INDIVIDUAL', 'BUSINESS', 'GOVERNMENT', 'WHOLESALE') NOT NULL DEFAULT 'BUSINESS',
    EMAIL               VARCHAR(100),
    PHONE               VARCHAR(20),
    BILLING_ADDRESS_ID  BIGINT UNSIGNED,
    SHIPPING_ADDRESS_ID BIGINT UNSIGNED,
    CREDIT_LIMIT        DECIMAL(15, 2) DEFAULT 0.00,
    TAX_ID              VARCHAR(50),
    IS_ACTIVE           BOOLEAN DEFAULT TRUE,
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY (BILLING_ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID) ON DELETE SET NULL,
    FOREIGN KEY (SHIPPING_ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID) ON DELETE SET NULL,
    INDEX IDX_CUSTOMER_CODE (CUSTOMER_CODE),
    INDEX IDX_CUSTOMER_TYPE (CUSTOMER_TYPE),
    INDEX IDX_CUSTOMER_ACTIVE (IS_ACTIVE)
) ENGINE=INNODB;

CREATE TABLE WAREHOUSE (
    WAREHOUSE_ID        BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    WAREHOUSE_CODE      VARCHAR(50) NOT NULL UNIQUE,
    WAREHOUSE_NAME      VARCHAR(200) NOT NULL,
    ADDRESS_ID          BIGINT UNSIGNED,
    MANAGER_NAME        VARCHAR(100),
    CAPACITY_M3         DECIMAL(12, 2),
    IS_ACTIVE           BOOLEAN DEFAULT TRUE,
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID) ON DELETE SET NULL,
    INDEX IDX_WAREHOUSE_CODE (WAREHOUSE_CODE),
    INDEX IDX_WAREHOUSE_ACTIVE (IS_ACTIVE)
) ENGINE=INNODB;

CREATE TABLE LOCATION (
    LOCATION_ID         BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    WAREHOUSE_ID        BIGINT UNSIGNED NOT NULL,
    LOCATION_CODE       VARCHAR(50) NOT NULL,
    LOCATION_TYPE       ENUM('RECEIVING', 'STORAGE', 'PICKING', 'SHIPPING', 'QUARANTINE', 'RETURNS') NOT NULL DEFAULT 'STORAGE',
    AISLE               VARCHAR(20),
    RACK                VARCHAR(20),
    SHELF               VARCHAR(20),
    BIN                 VARCHAR(20),
    IS_ACTIVE           BOOLEAN DEFAULT TRUE,
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSE(WAREHOUSE_ID) ON DELETE CASCADE,
    UNIQUE KEY UK_LOCATION_CODE_WAREHOUSE (WAREHOUSE_ID, LOCATION_CODE),
    INDEX IDX_LOCATION_WAREHOUSE (WAREHOUSE_ID),
    INDEX IDX_LOCATION_TYPE (LOCATION_TYPE)
) ENGINE=INNODB;

-- ============================================================
-- 3. INVENTORY TABLES
-- ============================================================

CREATE TABLE INVENTORY (
    INVENTORY_ID        BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_ID          BIGINT UNSIGNED NOT NULL,
    WAREHOUSE_ID        BIGINT UNSIGNED NOT NULL,
    LOCATION_ID         BIGINT UNSIGNED,
    QUANTITY_ON_HAND    INT NOT NULL DEFAULT 0,
    QUANTITY_RESERVED   INT NOT NULL DEFAULT 0,
    QUANTITY_AVAILABLE  INT GENERATED ALWAYS AS (QUANTITY_ON_HAND - QUANTITY_RESERVED) STORED,
    REORDER_LEVEL       INT NOT NULL DEFAULT 0,
    MAX_STOCK_LEVEL     INT,
    LAST_COUNTED_AT     TIMESTAMP NULL,
    UPDATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID) ON DELETE CASCADE,
    FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSE(WAREHOUSE_ID) ON DELETE CASCADE,
    FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION(LOCATION_ID) ON DELETE SET NULL,
    UNIQUE KEY UK_INVENTORY_PRODUCT_WAREHOUSE_LOC (PRODUCT_ID, WAREHOUSE_ID, LOCATION_ID),
    INDEX IDX_INVENTORY_PRODUCT (PRODUCT_ID),
    INDEX IDX_INVENTORY_WAREHOUSE (WAREHOUSE_ID),
    INDEX IDX_INVENTORY_LOCATION (LOCATION_ID),
    INDEX IDX_INVENTORY_REORDER (QUANTITY_AVAILABLE, REORDER_LEVEL)
) ENGINE=INNODB;

-- ============================================================
-- 4. SALES TABLES
-- ============================================================

CREATE TABLE SALES_ORDER (
    SALES_ORDER_ID      BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ORDER_NUMBER        VARCHAR(50) NOT NULL UNIQUE,
    CUSTOMER_ID         BIGINT UNSIGNED NOT NULL,
    BILLING_ADDRESS_ID  BIGINT UNSIGNED,
    SHIPPING_ADDRESS_ID BIGINT UNSIGNED,
    ORDER_DATE          DATE NOT NULL,
    REQUIRED_DATE       DATE,
    SHIPPED_DATE        DATE,
    SALES_REP_ID        BIGINT UNSIGNED,
    ORDER_STATUS        ENUM('DRAFT', 'CONFIRMED', 'PROCESSING', 'SHIPPED', 'DELIVERED', 'INVOICED', 'PAID', 'CANCELLED', 'RETURNED') NOT NULL DEFAULT 'DRAFT',
    SUBTOTAL            DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    TAX_AMOUNT          DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    SHIPPING_COST       DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    TOTAL_AMOUNT        DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    CURRENCY_CODE       CHAR(3) DEFAULT 'USD',
    NOTES               TEXT,
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(CUSTOMER_ID) ON DELETE RESTRICT,
    FOREIGN KEY (BILLING_ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID) ON DELETE SET NULL,
    FOREIGN KEY (SHIPPING_ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID) ON DELETE SET NULL,
    FOREIGN KEY (SALES_REP_ID) REFERENCES USER(USER_ID) ON DELETE SET NULL,
    INDEX IDX_SALES_ORDER_NUMBER (ORDER_NUMBER),
    INDEX IDX_SALES_ORDER_CUSTOMER (CUSTOMER_ID),
    INDEX IDX_SALES_ORDER_STATUS (ORDER_STATUS),
    INDEX IDX_SALES_ORDER_DATE (ORDER_DATE),
    INDEX IDX_SALES_ORDER_SHIPPED (SHIPPED_DATE)
) ENGINE=INNODB;

CREATE TABLE SALES_ORDER_LINE (
    LINE_ID             BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    SALES_ORDER_ID      BIGINT UNSIGNED NOT NULL,
    LINE_NUMBER         INT NOT NULL,
    PRODUCT_ID          BIGINT UNSIGNED NOT NULL,
    QUANTITY_ORDERED    INT NOT NULL DEFAULT 0,
    QUANTITY_SHIPPED    INT NOT NULL DEFAULT 0,
    UNIT_PRICE          DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    DISCOUNT_PCT        DECIMAL(5, 2) DEFAULT 0.00,
    LINE_TOTAL          DECIMAL(15, 2) GENERATED ALWAYS AS (QUANTITY_ORDERED * UNIT_PRICE * (1 - DISCOUNT_PCT/100)) STORED,
    WAREHOUSE_ID        BIGINT UNSIGNED,
    LINE_STATUS         ENUM('PENDING', 'PICKED', 'PACKED', 'SHIPPED', 'DELIVERED', 'RETURNED', 'CANCELLED') NOT NULL DEFAULT 'PENDING',
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (SALES_ORDER_ID) REFERENCES SALES_ORDER(SALES_ORDER_ID) ON DELETE CASCADE,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID) ON DELETE RESTRICT,
    FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSE(WAREHOUSE_ID) ON DELETE SET NULL,
    UNIQUE KEY UK_SALES_ORDER_LINE (SALES_ORDER_ID, LINE_NUMBER),
    INDEX IDX_SALES_LINE_ORDER (SALES_ORDER_ID),
    INDEX IDX_SALES_LINE_PRODUCT (PRODUCT_ID),
    INDEX IDX_SALES_LINE_STATUS (LINE_STATUS)
) ENGINE=INNODB;

-- ============================================================
-- 5. PURCHASE TABLES
-- ============================================================

CREATE TABLE PURCHASE_ORDER (
    PURCHASE_ORDER_ID   BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    PO_NUMBER           VARCHAR(50) NOT NULL UNIQUE,
    SUPPLIER_ID         BIGINT UNSIGNED NOT NULL,
    WAREHOUSE_ID        BIGINT UNSIGNED NOT NULL,
    ORDER_DATE          DATE NOT NULL,
    EXPECTED_DATE       DATE,
    RECEIVED_DATE       DATE,
    PO_STATUS           ENUM('DRAFT', 'SENT', 'ACKNOWLEDGED', 'PARTIALLY_RECEIVED', 'FULLY_RECEIVED', 'CLOSED', 'CANCELLED') NOT NULL DEFAULT 'DRAFT',
    SUBTOTAL            DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    TAX_AMOUNT          DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    SHIPPING_COST       DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    TOTAL_AMOUNT        DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    TERMS               VARCHAR(100),
    NOTES               TEXT,
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,

    FOREIGN KEY (SUPPLIER_ID) REFERENCES SUPPLIER(SUPPLIER_ID) ON DELETE RESTRICT,
    FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSE(WAREHOUSE_ID) ON DELETE RESTRICT,
    INDEX IDX_PO_NUMBER (PO_NUMBER),
    INDEX IDX_PO_SUPPLIER (SUPPLIER_ID),
    INDEX IDX_PO_STATUS (PO_STATUS),
    INDEX IDX_PO_ORDER_DATE (ORDER_DATE)
) ENGINE=INNODB;

CREATE TABLE PURCHASE_ORDER_LINE (
    PO_LINE_ID          BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    PURCHASE_ORDER_ID   BIGINT UNSIGNED NOT NULL,
    LINE_NUMBER         INT NOT NULL,
    PRODUCT_ID          BIGINT UNSIGNED NOT NULL,
    QUANTITY_ORDERED    INT NOT NULL DEFAULT 0,
    QUANTITY_RECEIVED   INT NOT NULL DEFAULT 0,
    UNIT_PRICE          DECIMAL(15, 2) NOT NULL DEFAULT 0.00,
    LINE_TOTAL          DECIMAL(15, 2) GENERATED ALWAYS AS (QUANTITY_ORDERED * UNIT_PRICE) STORED,
    WAREHOUSE_ID        BIGINT UNSIGNED,
    LINE_STATUS         ENUM('PENDING', 'PARTIALLY_RECEIVED', 'FULLY_RECEIVED', 'CANCELLED') NOT NULL DEFAULT 'PENDING',
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (PURCHASE_ORDER_ID) REFERENCES PURCHASE_ORDER(PURCHASE_ORDER_ID) ON DELETE CASCADE,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID) ON DELETE RESTRICT,
    FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSE(WAREHOUSE_ID) ON DELETE SET NULL,
    UNIQUE KEY UK_PO_LINE (PURCHASE_ORDER_ID, LINE_NUMBER),
    INDEX IDX_PO_LINE_PO (PURCHASE_ORDER_ID),
    INDEX IDX_PO_LINE_PRODUCT (PRODUCT_ID),
    INDEX IDX_PO_LINE_STATUS (LINE_STATUS)
) ENGINE=INNODB;

-- ============================================================
-- 6. LOGISTICS TABLES
-- ============================================================

CREATE TABLE SHIPMENT (
    SHIPMENT_ID         BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    TRACKING_NUMBER     VARCHAR(100),
    CARRIER_ID          BIGINT UNSIGNED,
    SHIPMENT_TYPE       ENUM('OUTBOUND', 'INBOUND', 'TRANSFER', 'RETURN') NOT NULL DEFAULT 'OUTBOUND',
    ORIGIN_WAREHOUSE_ID BIGINT UNSIGNED,
    DESTINATION_ADDRESS_ID BIGINT UNSIGNED,
    SHIP_DATE           DATE,
    ESTIMATED_ARRIVAL  DATE,
    ACTUAL_ARRIVAL      DATE,
    SHIPMENT_STATUS     ENUM('PLANNED', 'PICKED', 'PACKED', 'IN_TRANSIT', 'OUT_FOR_DELIVERY', 'DELIVERED', 'RETURNED', 'CANCELLED') NOT NULL DEFAULT 'PLANNED',
    SHIPPING_COST       DECIMAL(15, 2),
    WEIGHT_KG           DECIMAL(10, 3),
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (CARRIER_ID) REFERENCES CARRIER(CARRIER_ID) ON DELETE SET NULL,
    FOREIGN KEY (ORIGIN_WAREHOUSE_ID) REFERENCES WAREHOUSE(WAREHOUSE_ID) ON DELETE SET NULL,
    FOREIGN KEY (DESTINATION_ADDRESS_ID) REFERENCES ADDRESS(ADDRESS_ID) ON DELETE SET NULL,
    INDEX IDX_SHIPMENT_TRACKING (TRACKING_NUMBER),
    INDEX IDX_SHIPMENT_CARRIER (CARRIER_ID),
    INDEX IDX_SHIPMENT_STATUS (SHIPMENT_STATUS),
    INDEX IDX_SHIPMENT_DATE (SHIP_DATE)
) ENGINE=INNODB;

CREATE TABLE SHIPMENT_LINE (
    SHIPMENT_LINE_ID    BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    SHIPMENT_ID         BIGINT UNSIGNED NOT NULL,
    SALES_ORDER_LINE_ID BIGINT UNSIGNED,
    PRODUCT_ID          BIGINT UNSIGNED NOT NULL,
    QUANTITY_SHIPPED    INT NOT NULL DEFAULT 0,
    QUANTITY_DELIVERED  INT NOT NULL DEFAULT 0,
    WAREHOUSE_ID        BIGINT UNSIGNED,
    LOCATION_ID         BIGINT UNSIGNED,
    LINE_STATUS         ENUM('PICKED', 'PACKED', 'SHIPPED', 'IN_TRANSIT', 'DELIVERED', 'RETURNED') NOT NULL DEFAULT 'PICKED',
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (SHIPMENT_ID) REFERENCES SHIPMENT(SHIPMENT_ID) ON DELETE CASCADE,
    FOREIGN KEY (SALES_ORDER_LINE_ID) REFERENCES SALES_ORDER_LINE(LINE_ID) ON DELETE SET NULL,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID) ON DELETE RESTRICT,
    FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSE(WAREHOUSE_ID) ON DELETE SET NULL,
    FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION(LOCATION_ID) ON DELETE SET NULL,
    INDEX IDX_SHIPMENT_LINE_SHIPMENT (SHIPMENT_ID),
    INDEX IDX_SHIPMENT_LINE_PRODUCT (PRODUCT_ID),
    INDEX IDX_SHIPMENT_LINE_STATUS (LINE_STATUS)
) ENGINE=INNODB;

CREATE TABLE GOODS_RECEIPT (
    RECEIPT_ID          BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    RECEIPT_NUMBER      VARCHAR(50) NOT NULL UNIQUE,
    PURCHASE_ORDER_ID   BIGINT UNSIGNED,
    WAREHOUSE_ID        BIGINT UNSIGNED NOT NULL,
    RECEIPT_DATE        DATE NOT NULL,
    RECEIVED_BY_USER_ID BIGINT UNSIGNED,
    RECEIPT_STATUS      ENUM('PENDING', 'INSPECTING', 'PARTIALLY_ACCEPTED', 'FULLY_ACCEPTED', 'REJECTED') NOT NULL DEFAULT 'PENDING',
    TOTAL_ITEMS         INT NOT NULL DEFAULT 0,
    NOTES               TEXT,
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (PURCHASE_ORDER_ID) REFERENCES PURCHASE_ORDER(PURCHASE_ORDER_ID) ON DELETE SET NULL,
    FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSE(WAREHOUSE_ID) ON DELETE RESTRICT,
    FOREIGN KEY (RECEIVED_BY_USER_ID) REFERENCES USER(USER_ID) ON DELETE SET NULL,
    INDEX IDX_RECEIPT_NUMBER (RECEIPT_NUMBER),
    INDEX IDX_RECEIPT_PO (PURCHASE_ORDER_ID),
    INDEX IDX_RECEIPT_STATUS (RECEIPT_STATUS),
    INDEX IDX_RECEIPT_DATE (RECEIPT_DATE)
) ENGINE=INNODB;

CREATE TABLE GOODS_RECEIPT_LINE (
    RECEIPT_LINE_ID     BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    RECEIPT_ID          BIGINT UNSIGNED NOT NULL,
    PO_LINE_ID          BIGINT UNSIGNED,
    PRODUCT_ID          BIGINT UNSIGNED NOT NULL,
    QUANTITY_RECEIVED   INT NOT NULL DEFAULT 0,
    QUANTITY_ACCEPTED   INT NOT NULL DEFAULT 0,
    QUANTITY_REJECTED   INT NOT NULL DEFAULT 0,
    LOCATION_ID         BIGINT UNSIGNED,
    CONDITION_STATUS    ENUM('EXCELLENT', 'GOOD', 'FAIR', 'DAMAGED', 'DEFECTIVE') NOT NULL DEFAULT 'GOOD',
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (RECEIPT_ID) REFERENCES GOODS_RECEIPT(RECEIPT_ID) ON DELETE CASCADE,
    FOREIGN KEY (PO_LINE_ID) REFERENCES PURCHASE_ORDER_LINE(PO_LINE_ID) ON DELETE SET NULL,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID) ON DELETE RESTRICT,
    FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION(LOCATION_ID) ON DELETE SET NULL,
    INDEX IDX_RECEIPT_LINE_RECEIPT (RECEIPT_ID),
    INDEX IDX_RECEIPT_LINE_PRODUCT (PRODUCT_ID),
    INDEX IDX_RECEIPT_LINE_CONDITION (CONDITION_STATUS)
) ENGINE=INNODB;

CREATE TABLE STOCK_MOVEMENT (
    MOVEMENT_ID         BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_ID          BIGINT UNSIGNED NOT NULL,
    WAREHOUSE_ID        BIGINT UNSIGNED NOT NULL,
    LOCATION_ID         BIGINT UNSIGNED,
    MOVEMENT_TYPE       ENUM('RECEIPT', 'SALE', 'ADJUSTMENT', 'TRANSFER_IN', 'TRANSFER_OUT', 'RETURN', 'DAMAGE', 'EXPIRATION') NOT NULL,
    QUANTITY            INT NOT NULL,
    REFERENCE_ID        BIGINT UNSIGNED,
    REFERENCE_TYPE      VARCHAR(50),
    MOVEMENT_DATE       TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    USER_ID             BIGINT UNSIGNED,
    NOTES               TEXT,
    CREATED_AT          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCT(PRODUCT_ID) ON DELETE RESTRICT,
    FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSE(WAREHOUSE_ID) ON DELETE RESTRICT,
    FOREIGN KEY (LOCATION_ID) REFERENCES LOCATION(LOCATION_ID) ON DELETE SET NULL,
    FOREIGN KEY (USER_ID) REFERENCES USER(USER_ID) ON DELETE SET NULL,
    INDEX IDX_STOCK_MOVEMENT_PRODUCT (PRODUCT_ID),
    INDEX IDX_STOCK_MOVEMENT_WAREHOUSE (WAREHOUSE_ID),
    INDEX IDX_STOCK_MOVEMENT_TYPE (MOVEMENT_TYPE),
    INDEX IDX_STOCK_MOVEMENT_DATE (MOVEMENT_DATE),
    INDEX IDX_STOCK_MOVEMENT_REF (REFERENCE_TYPE, REFERENCE_ID)
) ENGINE=INNODB;

-- ============================================================
-- 7. ADD DEFERRED FOREIGN KEYS (Circular Dependencies)
-- ============================================================

ALTER TABLE USER ADD CONSTRAINT FK_USER_WAREHOUSE 
    FOREIGN KEY (WAREHOUSE_ID) REFERENCES WAREHOUSE(WAREHOUSE_ID) ON DELETE SET NULL;

-- ============================================================
-- 8. VIEWS FOR REPORTING
-- ============================================================

CREATE VIEW V_INVENTORY_STATUS AS
SELECT 
    P.PRODUCT_ID,
    P.SKU,
    P.PRODUCT_NAME,
    C.CATEGORY_NAME,
    S.SUPPLIER_NAME,
    W.WAREHOUSE_NAME,
    L.LOCATION_CODE,
    I.QUANTITY_ON_HAND,
    I.QUANTITY_RESERVED,
    I.QUANTITY_AVAILABLE,
    I.REORDER_LEVEL,
    CASE 
        WHEN I.QUANTITY_AVAILABLE <= I.REORDER_LEVEL THEN 'REORDER'
        WHEN I.QUANTITY_AVAILABLE = 0 THEN 'OUT_OF_STOCK'
        ELSE 'OK'
    END AS STOCK_STATUS
FROM PRODUCT P
LEFT JOIN CATEGORY C ON P.CATEGORY_ID = C.CATEGORY_ID
LEFT JOIN SUPPLIER S ON P.SUPPLIER_ID = S.SUPPLIER_ID
LEFT JOIN INVENTORY I ON P.PRODUCT_ID = I.PRODUCT_ID
LEFT JOIN WAREHOUSE W ON I.WAREHOUSE_ID = W.WAREHOUSE_ID
LEFT JOIN LOCATION L ON I.LOCATION_ID = L.LOCATION_ID
WHERE P.IS_ACTIVE = TRUE;

CREATE VIEW V_SALES_ORDER_SUMMARY AS
SELECT 
    SO.SALES_ORDER_ID,
    SO.ORDER_NUMBER,
    SO.ORDER_DATE,
    C.CUSTOMER_NAME,
    SO.ORDER_STATUS,
    SO.SUBTOTAL,
    SO.TAX_AMOUNT,
    SO.SHIPPING_COST,
    SO.TOTAL_AMOUNT,
    COUNT(SOL.LINE_ID) AS LINE_COUNT,
    SUM(SOL.QUANTITY_ORDERED) AS TOTAL_ITEMS_ORDERED,
    SUM(SOL.QUANTITY_SHIPPED) AS TOTAL_ITEMS_SHIPPED
FROM SALES_ORDER SO
JOIN CUSTOMER C ON SO.CUSTOMER_ID = C.CUSTOMER_ID
LEFT JOIN SALES_ORDER_LINE SOL ON SO.SALES_ORDER_ID = SOL.SALES_ORDER_ID
GROUP BY SO.SALES_ORDER_ID, SO.ORDER_NUMBER, SO.ORDER_DATE, C.CUSTOMER_NAME, 
         SO.ORDER_STATUS, SO.SUBTOTAL, SO.TAX_AMOUNT, SO.SHIPPING_COST, SO.TOTAL_AMOUNT;

CREATE VIEW V_PURCHASE_ORDER_STATUS AS
SELECT 
    PO.PURCHASE_ORDER_ID,
    PO.PO_NUMBER,
    PO.ORDER_DATE,
    S.SUPPLIER_NAME,
    W.WAREHOUSE_NAME,
    PO.PO_STATUS,
    PO.TOTAL_AMOUNT,
    COUNT(POL.PO_LINE_ID) AS LINE_COUNT,
    SUM(POL.QUANTITY_ORDERED) AS TOTAL_ITEMS_ORDERED,
    SUM(POL.QUANTITY_RECEIVED) AS TOTAL_ITEMS_RECEIVED
FROM PURCHASE_ORDER PO
JOIN SUPPLIER S ON PO.SUPPLIER_ID = S.SUPPLIER_ID
JOIN WAREHOUSE W ON PO.WAREHOUSE_ID = W.WAREHOUSE_ID
LEFT JOIN PURCHASE_ORDER_LINE POL ON PO.PURCHASE_ORDER_ID = POL.PURCHASE_ORDER_ID
GROUP BY PO.PURCHASE_ORDER_ID, PO.PO_NUMBER, PO.ORDER_DATE, S.SUPPLIER_NAME, 
         W.WAREHOUSE_NAME, PO.PO_STATUS, PO.TOTAL_AMOUNT;

-- ============================================================
-- 9. TRIGGERS FOR AUDIT & INTEGRITY
-- ============================================================

DELIMITER //

CREATE TRIGGER TRG_SALES_ORDER_LINE_AFTER_INSERT
AFTER INSERT ON SALES_ORDER_LINE
FOR EACH ROW
BEGIN
    UPDATE SALES_ORDER 
    SET SUBTOTAL = (SELECT SUM(LINE_TOTAL) FROM SALES_ORDER_LINE WHERE SALES_ORDER_ID = NEW.SALES_ORDER_ID),
        TOTAL_AMOUNT = SUBTOTAL + TAX_AMOUNT + SHIPPING_COST
    WHERE SALES_ORDER_ID = NEW.SALES_ORDER_ID;
END //

CREATE TRIGGER TRG_PURCHASE_ORDER_LINE_AFTER_INSERT
AFTER INSERT ON PURCHASE_ORDER_LINE
FOR EACH ROW
BEGIN
    UPDATE PURCHASE_ORDER 
    SET SUBTOTAL = (SELECT SUM(LINE_TOTAL) FROM PURCHASE_ORDER_LINE WHERE PURCHASE_ORDER_ID = NEW.PURCHASE_ORDER_ID),
        TOTAL_AMOUNT = SUBTOTAL + TAX_AMOUNT + SHIPPING_COST
    WHERE PURCHASE_ORDER_ID = NEW.PURCHASE_ORDER_ID;
END //

CREATE TRIGGER TRG_GOODS_RECEIPT_LINE_AFTER_INSERT
AFTER INSERT ON GOODS_RECEIPT_LINE
FOR EACH ROW
BEGIN
    -- Update inventory
    INSERT INTO INVENTORY (PRODUCT_ID, WAREHOUSE_ID, LOCATION_ID, QUANTITY_ON_HAND)
    VALUES (NEW.PRODUCT_ID, 
            (SELECT WAREHOUSE_ID FROM GOODS_RECEIPT WHERE RECEIPT_ID = NEW.RECEIPT_ID),
            NEW.LOCATION_ID,
            NEW.QUANTITY_ACCEPTED)
    ON DUPLICATE KEY UPDATE 
        QUANTITY_ON_HAND = QUANTITY_ON_HAND + NEW.QUANTITY_ACCEPTED,
        UPDATED_AT = CURRENT_TIMESTAMP;

    -- Log stock movement
    INSERT INTO STOCK_MOVEMENT (PRODUCT_ID, WAREHOUSE_ID, LOCATION_ID, MOVEMENT_TYPE, 
                                QUANTITY, REFERENCE_ID, REFERENCE_TYPE, NOTES)
    VALUES (NEW.PRODUCT_ID,
            (SELECT WAREHOUSE_ID FROM GOODS_RECEIPT WHERE RECEIPT_ID = NEW.RECEIPT_ID),
            NEW.LOCATION_ID,
            'RECEIPT',
            NEW.QUANTITY_ACCEPTED,
            NEW.RECEIPT_ID,
            'GOODS_RECEIPT',
            CONCAT('Receipt: ', NEW.RECEIPT_ID));
END //

DELIMITER ;

-- ============================================================
-- 10. SAMPLE DATA INSERTION
-- ============================================================

INSERT INTO ADDRESS (ADDRESS_LINE1, CITY, STATE_PROVINCE, POSTAL_CODE, COUNTRY_CODE) VALUES
('123 MAIN ST', 'NEW YORK', 'NY', '10001', 'US'),
('456 OAK AVE', 'LOS ANGELES', 'CA', '90001', 'US'),
('789 PINE RD', 'CHICAGO', 'IL', '60601', 'US'),
('321 ELM BLVD', 'HOUSTON', 'TX', '77001', 'US');

INSERT INTO CARRIER (CARRIER_NAME, CARRIER_CODE, SERVICE_TYPE, CONTACT_PHONE) VALUES
('FEDEX', 'FEDEX_GROUND', 'GROUND', '1-800-463-3339'),
('UPS', 'UPS_STANDARD', 'STANDARD', '1-800-742-5877'),
('DHL', 'DHL_EXPRESS', 'EXPRESS', '1-800-225-5345');

INSERT INTO USER (USERNAME, EMAIL, FIRST_NAME, LAST_NAME, ROLE) VALUES
('ADMIN_USER', 'ADMIN@COMPANY.COM', 'SYSTEM', 'ADMIN', 'ADMIN'),
('WH_MANAGER_1', 'MANAGER1@COMPANY.COM', 'JOHN', 'SMITH', 'MANAGER'),
('SALES_REP_1', 'SALES1@COMPANY.COM', 'JANE', 'DOE', 'SALES_REP');

INSERT INTO CATEGORY (CATEGORY_NAME, DESCRIPTION) VALUES
('ELECTRONICS', 'ELECTRONIC DEVICES AND ACCESSORIES'),
('FURNITURE', 'OFFICE AND HOME FURNITURE'),
('CLOTHING', 'APPAREL AND ACCESSORIES');

INSERT INTO SUPPLIER (SUPPLIER_CODE, SUPPLIER_NAME, CONTACT_NAME, EMAIL, PHONE, ADDRESS_ID, PAYMENT_TERMS) VALUES
('SUP001', 'TECH SUPPLY CO', 'MIKE JOHNSON', 'MIKE@TECHSUPPLY.COM', '555-0101', 1, 'NET_30'),
('SUP002', 'HOME GOODS INC', 'SARAH WILLIAMS', 'SARAH@HOMEGOODS.COM', '555-0102', 2, 'NET_45');

INSERT INTO PRODUCT (SKU, PRODUCT_NAME, DESCRIPTION, CATEGORY_ID, SUPPLIER_ID, UNIT_PRICE, UNIT_COST) VALUES
('LAPTOP-001', 'PRO LAPTOP 15"', 'HIGH-PERFORMANCE LAPTOP', 1, 1, 1299.99, 899.99),
('DESK-001', 'EXECUTIVE DESK', 'L-SHAPED EXECUTIVE DESK', 2, 2, 599.99, 349.99),
('SHIRT-001', 'COTTON POLO SHIRT', 'PREMIUM COTTON POLO', 3, 2, 49.99, 24.99);

INSERT INTO CUSTOMER (CUSTOMER_CODE, CUSTOMER_NAME, CUSTOMER_TYPE, EMAIL, PHONE, BILLING_ADDRESS_ID, SHIPPING_ADDRESS_ID, CREDIT_LIMIT) VALUES
('CUST001', 'ACME CORPORATION', 'BUSINESS', 'ORDERS@ACME.COM', '555-0201', 3, 3, 50000.00),
('CUST002', 'GLOBAL RETAIL LLC', 'WHOLESALE', 'BUYING@GLOBAL.COM', '555-0202', 4, 4, 100000.00);

INSERT INTO WAREHOUSE (WAREHOUSE_CODE, WAREHOUSE_NAME, ADDRESS_ID, MANAGER_NAME, CAPACITY_M3) VALUES
('WH-EAST', 'EAST COAST DISTRIBUTION CENTER', 1, 'JOHN SMITH', 50000.00),
('WH-WEST', 'WEST COAST DISTRIBUTION CENTER', 2, 'JANE DOE', 45000.00);

UPDATE USER SET WAREHOUSE_ID = 1 WHERE USER_ID = 2;

INSERT INTO LOCATION (WAREHOUSE_ID, LOCATION_CODE, LOCATION_TYPE, AISLE, RACK, SHELF, BIN) VALUES
(1, 'A-01-R01-S01-B01', 'STORAGE', 'A01', 'R01', 'S01', 'B01'),
(1, 'A-01-R01-S01-B02', 'STORAGE', 'A01', 'R01', 'S01', 'B02'),
(1, 'RCV-01', 'RECEIVING', 'RCV', '01', '01', '01'),
(2, 'B-01-R01-S01-B01', 'STORAGE', 'B01', 'R01', 'S01', 'B01');

INSERT INTO INVENTORY (PRODUCT_ID, WAREHOUSE_ID, LOCATION_ID, QUANTITY_ON_HAND, QUANTITY_RESERVED, REORDER_LEVEL, MAX_STOCK_LEVEL) VALUES
(1, 1, 1, 150, 10, 50, 500),
(2, 1, 2, 75, 5, 25, 200),
(3, 2, 4, 300, 20, 100, 1000);

INSERT INTO SALES_ORDER (ORDER_NUMBER, CUSTOMER_ID, BILLING_ADDRESS_ID, SHIPPING_ADDRESS_ID, ORDER_DATE, REQUIRED_DATE, SALES_REP_ID, ORDER_STATUS, SUBTOTAL, TAX_AMOUNT, SHIPPING_COST, TOTAL_AMOUNT) VALUES
('SO-2026-0001', 1, 3, 3, '2026-04-20', '2026-04-25', 3, 'CONFIRMED', 1349.98, 107.00, 25.00, 1481.98);

INSERT INTO SALES_ORDER_LINE (SALES_ORDER_ID, LINE_NUMBER, PRODUCT_ID, QUANTITY_ORDERED, QUANTITY_SHIPPED, UNIT_PRICE, DISCOUNT_PCT, WAREHOUSE_ID, LINE_STATUS) VALUES
(1, 1, 1, 1, 0, 1299.99, 0.00, 1, 'PENDING'),
(1, 2, 3, 1, 0, 49.99, 0.00, 2, 'PENDING');

INSERT INTO PURCHASE_ORDER (PO_NUMBER, SUPPLIER_ID, WAREHOUSE_ID, ORDER_DATE, EXPECTED_DATE, PO_STATUS, SUBTOTAL, TAX_AMOUNT, SHIPPING_COST, TOTAL_AMOUNT) VALUES
('PO-2026-0001', 1, 1, '2026-04-15', '2026-04-30', 'SENT', 4499.95, 360.00, 150.00, 5009.95);

INSERT INTO PURCHASE_ORDER_LINE (PURCHASE_ORDER_ID, LINE_NUMBER, PRODUCT_ID, QUANTITY_ORDERED, QUANTITY_RECEIVED, UNIT_PRICE, WAREHOUSE_ID, LINE_STATUS) VALUES
(1, 1, 1, 5, 0, 899.99, 1, 'PENDING');

COMMIT;
