# Generated by Django 5.0.6 on 2026-04-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commune',
            name='NAME_EN',
            field=models.CharField(blank=True, db_column='NAME_EN', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='commune',
            name='NAME_KH',
            field=models.CharField(blank=True, db_column='NAME_KH', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='NAME_EN',
            field=models.CharField(blank=True, db_column='NAME_EN', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='NAME_EN',
            field=models.CharField(blank=True, db_column='NAME_EN', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='district',
            name='NAME_KH',
            field=models.CharField(blank=True, db_column='NAME_KH', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='province',
            name='NAME_EN',
            field=models.CharField(blank=True, db_column='NAME_EN', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='province',
            name='NAME_KH',
            field=models.CharField(blank=True, db_column='NAME_KH', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='village',
            name='NAME_KH',
            field=models.CharField(blank=True, db_column='NAME_KH', max_length=150, null=True),
        ),
    ]
