# Generated by Django 5.0.6 on 2026-04-23 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('CODE', models.CharField(db_column='CODE', max_length=15, unique=True)),
                ('USERNAME', models.CharField(db_column='USERNAME', max_length=255, unique=True)),
                ('EMAIL', models.EmailField(db_column='EMAIL', max_length=255, unique=True)),
                ('PASSWORD_HASH', models.CharField(db_column='PASSWORD_HASH', max_length=255)),
                ('USER_TYPE', models.CharField(db_column='USER_TYPE', default='USER', max_length=20)),
                ('EMAIL_VERIFIED', models.BooleanField(db_column='EMAIL_VERIFIED', default=False)),
                ('PHONE_VERIFIED', models.BooleanField(db_column='PHONE_VERIFIED', default=False)),
                ('STATUS', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('LOCKED', 'Locked'), ('PENDING', 'Pending'), ('SUSPENDED', 'Suspended')], default='ACTIVE', max_length=20)),
                ('IS_SUPERUSER', models.BooleanField(db_column='IS_SUPERUSER', default=False)),
                ('FAILED_LOGIN_ATTEMPTS', models.IntegerField(db_column='FAILED_LOGIN_ATTEMPTS', default=0)),
                ('LOCKED_UNTIL', models.DateTimeField(blank=True, db_column='LOCKED_UNTIL', max_length=6, null=True)),
                ('LAST_LOGIN', models.DateTimeField(blank=True, db_column='LAST_LOGIN', max_length=6, null=True)),
                ('PASSWORD_CHANGED_AT', models.DateTimeField(blank=True, db_column='PASSWORD_CHANGED_AT', max_length=6, null=True)),
                ('IS_DELETED', models.BooleanField(db_column='IS_DELETED', default=False)),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('UPDATED_AT', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('CREATED_BY', models.ForeignKey(db_column='CREATED_BY', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_created', to=settings.AUTH_USER_MODEL)),
                ('UPDATED_BY', models.ForeignKey(blank=True, db_column='UPDATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'USERS',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('name_user_profile_id', models.OneToOneField(db_column='USER_ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('NAME', models.CharField(db_column='NAME', max_length=100)),
                ('NAME_ENGLISH', models.CharField(blank=True, db_column='NAME_ENGLISH', max_length=100, null=True)),
                ('GENDER', models.CharField(blank=True, db_column='GENDER', max_length=20, null=True)),
                ('DOB', models.DateField(blank=True, db_column='DOB', null=True)),
                ('POB', models.TextField(blank=True, db_column='POB', null=True)),
                ('MARITAL_STATUS', models.CharField(blank=True, db_column='MARITAL_STATUS', max_length=20, null=True)),
                ('NATIONAL_ID', models.CharField(blank=True, db_column='NATIONAL_ID', max_length=25, null=True)),
                ('NATIONALITY', models.CharField(blank=True, db_column='NATIONALITY', max_length=100, null=True)),
                ('OCCUPATION', models.CharField(blank=True, db_column='OCCUPATION', max_length=100, null=True)),
                ('ADDRESS_LINE1', models.CharField(blank=True, db_column='ADDRESS_LINE1', max_length=255, null=True)),
                ('ADDRESS_LINE2', models.CharField(blank=True, db_column='ADDRESS_LINE2', max_length=255, null=True)),
                ('ZIP_CODE', models.CharField(blank=True, db_column='ZIP_CODE', max_length=20, null=True)),
                ('POSTAL_CODE', models.CharField(blank=True, db_column='POSTAL_CODE', max_length=20, null=True)),
                ('PROFILE_PICTURE_URL', models.URLField(blank=True, db_column='PROFILE_PICTURE_URL', max_length=500, null=True)),
                ('SIGNATURE_URL', models.URLField(blank=True, db_column='SIGNATURE_URL', max_length=500, null=True)),
                ('BIO', models.TextField(blank=True, db_column='BIO', null=True)),
                ('LANGUAGE_PREFERENCE', models.CharField(db_column='LANGUAGE_PREFERENCE', default='km', max_length=2)),
                ('TIMEZONE', models.CharField(db_column='TIMEZONE', default='Asia/Phnom_Penh', max_length=50)),
                ('IS_VERIFIED', models.BooleanField(db_column='IS_VERIFIED', default=False)),
                ('FACEBOOK_LINK', models.URLField(blank=True, db_column='FACEBOOK_LINK', max_length=255, null=True)),
                ('TIKTOK_LINK', models.URLField(blank=True, db_column='TIKTOK_LINK', max_length=255, null=True)),
                ('LINKEDIN_LINK', models.URLField(blank=True, db_column='LINKEDIN_LINK', max_length=255, null=True)),
                ('WEBSITE', models.URLField(blank=True, db_column='WEBSITE', max_length=255, null=True)),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('UPDATED_AT', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
            ],
            options={
                'db_table': 'USER_PROFILES',
            },
        ),
        migrations.CreateModel(
            name='AuthAuditLog',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('EVENT_TYPE', models.CharField(db_column='EVENT_TYPE', max_length=50)),
                ('EVENT_DESCRIPTION', models.TextField(blank=True, db_column='EVENT_DESCRIPTION', null=True)),
                ('IP_ADDRESS', models.GenericIPAddressField(blank=True, db_column='IP_ADDRESS', null=True)),
                ('USER_AGENT', models.CharField(blank=True, db_column='USER_AGENT', max_length=500, null=True)),
                ('SUCCESS', models.BooleanField(db_column='SUCCESS', default=True)),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('CREATED_BY', models.ForeignKey(db_column='CREATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authauditlog_updated', to=settings.AUTH_USER_MODEL)),
                ('USER_ID', models.ForeignKey(db_column='USER_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authauditlog_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'AUTH_AUDIT_LOG',
            },
        ),
        migrations.CreateModel(
            name='ForgotOrResetPassword',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('TOKEN_HASH', models.CharField(db_column='TOKEN_HASH', max_length=255)),
                ('EXPIRES_AT', models.DateTimeField(db_column='EXPIRES_AT')),
                ('IS_USED', models.BooleanField(db_column='IS_USED', default=False)),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('CREATED_BY', models.ForeignKey(db_column='CREATED_BY', on_delete=django.db.models.deletion.PROTECT, related_name='created_password_reset_tokens', to=settings.AUTH_USER_MODEL)),
                ('USER_ID', models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PASSWORD_RESET_TOKENS',
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('LOGIN_TIME', models.DateTimeField(auto_now_add=True, db_column='LOGIN_TIME')),
                ('LOGOUT_TIME', models.DateTimeField(blank=True, db_column='LOGOUT_TIME', null=True)),
                ('IP_ADDRESS', models.GenericIPAddressField(blank=True, db_column='IP_ADDRESS', null=True)),
                ('USER_AGENT', models.TextField(blank=True, db_column='USER_AGENT', null=True)),
                ('LOGIN_STATUS', models.CharField(db_column='LOGIN_STATUS', max_length=10)),
                ('FAILURE_REASON', models.CharField(blank=True, db_column='FAILURE_REASON', max_length=255, null=True)),
                ('DEVICE_TYPE', models.CharField(blank=True, db_column='DEVICE_TYPE', max_length=50, null=True)),
                ('BROWSER', models.CharField(blank=True, db_column='BROWSER', max_length=50, null=True)),
                ('OS', models.CharField(blank=True, db_column='OS', max_length=50, null=True)),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('USER_ID', models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'LOGIN_HISTORY',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('CODE', models.CharField(db_column='PERMISSION_CODE', max_length=100, unique=True)),
                ('NAME', models.CharField(db_column='PERMISSION_NAME', max_length=150)),
                ('DESCRIPTION', models.TextField(blank=True, db_column='DESCRIPTION', null=True)),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('UPDATED_AT', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('CREATED_BY', models.ForeignKey(db_column='CREATED_BY', on_delete=django.db.models.deletion.PROTECT, related_name='permission_created_by', to=settings.AUTH_USER_MODEL)),
                ('UPDATED_BY', models.ForeignKey(blank=True, db_column='UPDATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permission_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PERMISSIONS',
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('TOKEN_HASH', models.CharField(db_column='TOKEN_HASH', max_length=512)),
                ('USER_AGENT', models.CharField(blank=True, db_column='USER_AGENT', max_length=500, null=True)),
                ('IP_ADDRESS', models.GenericIPAddressField(blank=True, db_column='IP_ADDRESS', null=True)),
                ('EXPIRES_AT', models.DateTimeField(db_column='EXPIRES_AT')),
                ('IS_REVOKED', models.BooleanField(db_column='IS_REVOKED', default=False)),
                ('REVOKED_AT', models.DateTimeField(blank=True, db_column='REVOKED_AT', null=True)),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('UPDATED_AT', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('CREATED_BY', models.ForeignKey(db_column='CREATED_BY', on_delete=django.db.models.deletion.PROTECT, related_name='refreshtoken_created_by', to=settings.AUTH_USER_MODEL)),
                ('UPDATED_BY', models.ForeignKey(blank=True, db_column='UPDATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refreshtoken_updated_by', to=settings.AUTH_USER_MODEL)),
                ('USER_ID', models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'REFRESH_TOKENS',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('CODE', models.CharField(max_length=50, unique=True)),
                ('NAME', models.CharField(db_column='ROLE_NAME', max_length=100)),
                ('DESCRIPTION', models.TextField(blank=True, null=True)),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('UPDATED_AT', models.DateTimeField(auto_now=True)),
                ('CREATED_BY', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='role_created_by', to=settings.AUTH_USER_MODEL)),
                ('UPDATED_BY', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ROLES',
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('UPDATED_AT', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('CREATED_BY', models.ForeignKey(db_column='CREATED_BY', on_delete=django.db.models.deletion.PROTECT, related_name='rolepermission_created_by', to=settings.AUTH_USER_MODEL)),
                ('PERMISSION_ID', models.ForeignKey(db_column='PERMISSION_ID', on_delete=django.db.models.deletion.CASCADE, to='accounts.permission')),
                ('ROLE_ID', models.ForeignKey(db_column='ROLE_ID', on_delete=django.db.models.deletion.CASCADE, to='accounts.role')),
                ('UPDATED_BY', models.ForeignKey(blank=True, db_column='UPDATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rolepermission_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ROLE_PERMISSIONS',
            },
        ),
        migrations.CreateModel(
            name='UserOTP',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('OTP_CODE', models.CharField(db_column='OTP_CODE', max_length=10)),
                ('OTP_TYPE', models.CharField(db_column='OTP_TYPE', max_length=30)),
                ('EXPIRES_AT', models.DateTimeField(db_column='EXPIRES_AT')),
                ('IS_USED', models.BooleanField(db_column='IS_USED', default=False)),
                ('ATTEMPTS', models.IntegerField(db_column='ATTEMPTS', default=0)),
                ('MAX_ATTEMPTS', models.IntegerField(db_column='MAX_ATTEMPTS', default=5)),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('USER_ID', models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.CASCADE, related_name='user_otps', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'USER_OTP',
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('ID', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('CREATED_AT', models.DateTimeField(auto_now_add=True, db_column='CREATED_AT')),
                ('UPDATED_AT', models.DateTimeField(auto_now=True, db_column='UPDATED_AT')),
                ('CREATED_BY', models.ForeignKey(db_column='CREATED_BY', on_delete=django.db.models.deletion.PROTECT, related_name='userrole_created_by', to=settings.AUTH_USER_MODEL)),
                ('ROLE_ID', models.ForeignKey(db_column='ROLE_ID', on_delete=django.db.models.deletion.CASCADE, related_name='userrole_role_id', to='accounts.role')),
                ('UPDATED_BY', models.ForeignKey(blank=True, db_column='UPDATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='userrole_updated_by', to=settings.AUTH_USER_MODEL)),
                ('USER_ID', models.ForeignKey(db_column='USER_ID', on_delete=django.db.models.deletion.CASCADE, related_name='userrole_user_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'USER_ROLES',
            },
        ),
    ]
