# Generated by Django 5.0.6 on 2026-04-23 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('admin_address', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='COMMUNE_ID',
            field=models.ForeignKey(blank=True, db_column='COMMUNE_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_address.commune'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='COUNTRY_ID',
            field=models.ForeignKey(db_column='COUNTRY_ID', default=1, on_delete=django.db.models.deletion.PROTECT, to='admin_address.country'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='CREATED_BY',
            field=models.ForeignKey(db_column='CREATED_BY', on_delete=django.db.models.deletion.PROTECT, related_name='created_user_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='DISTRICT_ID',
            field=models.ForeignKey(blank=True, db_column='DISTRICT_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_address.district'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='PROVINCE_ID',
            field=models.ForeignKey(blank=True, db_column='PROVINCE_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_address.province'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='UPDATED_BY',
            field=models.ForeignKey(blank=True, db_column='UPDATED_BY', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_user_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='VILLAGE_ID',
            field=models.ForeignKey(blank=True, db_column='VILLAGE_ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='admin_address.village'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('ROLE_ID', 'PERMISSION_ID')},
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('USER_ID', 'ROLE_ID')},
        ),
    ]
