"""
Django settings for ANGKORTRANS project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import environ
import os

# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# # BASE_DIR = Path(__file__).resolve().parent.parent

# # Initialize environment variables
env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)
# # Set the project base directory
# # Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# # Take environment variables from .env file
# # Read .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# # Then use env
DEBUG = env('DEBUG')

SERVER_PORT = env('SERVER_PORT')

# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# # Raises Django's ImproperlyConfigured
# # exception if SECRET_KEY not in os.environ
SECRET_KEY = env('SECRET_KEY')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[
    "127.0.0.1",
    "localhost",
    "0.0.0.0",          # useful if you want to access from other devices
    # add your domain / IP here for production
])
# # Optional: make runserver bind to 0.0.0.0 by default in dev
if DEBUG:
    ALLOWED_HOSTS += ["0.0.0.0"]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# SECURITY WARNING: don't run with debug turned on in production!
# OpenRouter Configuration
OPENROUTER_API_KEY = env('OPENROUTER_API_KEY')
OPENROUTER_API_URL = 'https://openrouter.ai/api/v1/chat/completions'
# OPENROUTER_MODEL='qwen/qwen-2.5-72b-instruct'  #Best for Khmer
# OPENROUTER_MODEL='qwen/qwen-3-vl-8b'  #Best for Khmer
OPENROUTER_MODEL=env('OPENROUTER_MODEL')

# SIMPLE_JWT = { #This makes SimpleJWT use: (user.ID) instead of:(user.id)
#     'USER_ID_FIELD': 'ID',
#     # 'USER_ID_FIELD': 'ID',
#     'USER_ID_CLAIM': 'user_id',
# }


# Disable trailing slash for API endpoints
APPEND_SLASH = False


SIMPLE_JWT = {
    "AUTH_HEADER_TYPES": ("Bearer",),
    "USER_ID_FIELD": "ID",
    "USER_ID_CLAIM": "user_id",
    "CHECK_USER_IS_ACTIVE": False,  # ⚠️ disable check
}

# ============================================
# SECURITY SETTINGS
# ============================================

if DEBUG:
    # LOCAL DEVELOPMENT
    SECURE_SSL_REDIRECT = False

    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

    SECURE_HSTS_SECONDS = 0
    SECURE_HSTS_INCLUDE_SUBDOMAINS = False
    SECURE_HSTS_PRELOAD = False

else:
    # PRODUCTION
    SECURE_SSL_REDIRECT = True

    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

""" Security Side"""
# SECRET_KEY = os.getenv('DJANGO_SECRET_KEY')  # Must be strong & from env

# Prevent clickjacking
X_FRAME_OPTIONS = 'DENY'

# Content Security Policy (recommended)
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_BROWSER_XSS_FILTER = True


AUTH_USER_MODEL = 'accounts.Users' #for django auth system, but we are using custom auth with JWT, so we will handle user authentication manually in views and serializers. This allows us to have more control over the user model and authentication process without being tied to Django's built-in auth system. We can still use Django's password hashing utilities for security, but we won't be using the full AbstractBaseUser or PermissionsMixin features.


# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
# Security & Rate Limiting
'django_ratelimit',
    'axes',                    # Brute force protection
    "channels",

   # your apps...
    'accounts',
    'api_app',
    'inventory',
    'admin_address',
    'apps',
    'apps.notifications',
    'cms',
    'cms.artworks',
    'cms.comments',
    'AI',

    # DRF + Spectacular
    'rest_framework',          # if you use DRF
    'rest_framework_simplejwt',
    'drf_spectacular',         # ← add here, preferably at the bottom

]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',# ← Must be near the top
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Add this line:
    'axes.middleware.AxesMiddleware',
]
# Add this to silence ratelimit cache warning in development
SILENCED_SYSTEM_CHECKS = [
    'django_ratelimit.E003',
    'django_ratelimit.W001',
]
ROOT_URLCONF = 'ANGKORTRANS.urls'

# IMPORTANT: Fix for axes.W003
AUTHENTICATION_BACKENDS = [
    'axes.backends.AxesStandaloneBackend',   # ← Must be first
    'django.contrib.auth.backends.ModelBackend',
]

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        "rest_framework.permissions.AllowAny",
        # "rest_framework.permissions.IsAuthenticated"
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
    ],
    'DEFAULT_THROTTLE_CLASSES': [
        'rest_framework.throttling.AnonRateThrottle',
        'rest_framework.throttling.UserRateThrottle',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '60/min',       # Anonymous users
        'user': '300/min',      # Logged-in users
        'login': '5/min',           # you can define custom scopes
    },
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',  # Disable browsable API in prod
    ],
}

# ======================
# django-axes Settings (Brute Force Protection)
# ======================
# django-axes (brute force protection)
AXES_FAILURE_LIMIT = 5
AXES_LOCKOUT_TIME = 30  # minutes
AXES_COOLOFF_TIME = 30
# AXES_LOCKOUT_TEMPLATE = 'lockout.html'
AXES_RESET_ON_SUCCESS = True
AXES_VERBOSE = True
AXES_LOCKOUT_TEMPLATE = None
""" 
# Example for login view
from rest_framework.throttling import AnonRateThrottle

class LoginThrottle(AnonRateThrottle):
    rate = '5/min'

# In your view
class LoginView(...):
    throttle_classes = [LoginThrottle]


pip install django-ratelimit django-axes
pip install django-ratelimit
""" 
# Central API Configuration
API_VERSION = '1.0.0'          # ← Change this when you release a new version
APP_TITLE = 'AngkorTrans API'
SPECTACULAR_SETTINGS = {
    'TITLE': APP_TITLE,                    # Correct key is 'TITLE' (not 'APP_TITLE')
    'DESCRIPTION': 'Ancient Powered Neural Translation API - Khmer ↔ English & 100+ languages',
    # 'VERSION': '1.0.0',
    'VERSION': API_VERSION,          # ← This will be used in docs too
    'SERVE_INCLUDE_SCHEMA': False,
    'SWAGGER_UI_DIST': 'https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/5.17.14/',
    'SWAGGER_UI_FAVICON_HREF': 'https://yourdomain.com/static/favicon.ico',  # optional
    # To use custom template:
    'SWAGGER_UI_TEMPLATE': 'drf_spectacular/swagger_ui.html',   # This line enables your custom file
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': True,
        'defaultModelsExpandDepth': 1,
        'docExpansion': 'none',
    },
    'REDOC_SETTINGS': {
        'theme': {
            'primaryColor': '#ff3366',
            'backgroundColor': '#0a0a0a',
        }
    },
}


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': [],
        #  "DIRS": [BASE_DIR / "templates"],  # IMPORTANT
        "DIRS": [os.path.join(BASE_DIR, "templates")],  # ✅ IMPORTANT
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
# CORS Settings - Allow Nuxt dev server
# ============================================
# CORS
# ============================================

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "OPTIONS",
]

CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

# Important for API
CORS_URLS_REGEX = r'^/api/.*$'

WSGI_APPLICATION = 'ANGKORTRANS.wsgi.application'

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
 
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
 
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': env('DB_NAME', default='ANGKORTRANS'),
        # 'NAME': 'ANGKORTRANS',           # Main / shared database
        'USER': env('DB_USER', default='root'),
        'PASSWORD': env('DB_PASSWORD', default=''),
        'HOST': env('DB_HOST', default='localhost'),  # or your server IP
        'PORT': env('DB_PORT', default='3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            "ssl": {"ssl-mode": "REQUIRED"},
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
        },
        'CONN_MAX_AGE': 600,   # Connection pooling            # Keep connection alive a bit longer
        "ATOMIC_REQUESTS": False,   # ✅ explicitly safe
    },
    # # Optional: Add more static client databases (same server, different NAME)
    # 'client1': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'angkortrans_client1',
    #     'USER': 'your_mysql_user',
    #     'PASSWORD': 'your_mysql_password',
    #     'HOST': 'localhost',
    #     'PORT': '3306',
    #     'OPTIONS': {'charset': 'utf8mb4'},
    # },
    # 'client2': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'angkortrans_client2',
    #     'USER': 'your_mysql_user',
    #     'PASSWORD': 'your_mysql_password',
    #     'HOST': 'localhost',
    #     'PORT': '3306',
    #     'OPTIONS': {'charset': 'utf8mb4'},
    # },
    # Add more static clients here as needed...
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
# Optional: Close connections quickly for dynamic use
DATABASE_ROUTERS = []  # You can add custom router if needed

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# Google AI Studio API Key
GOOGLE_AI_API_KEY = env('GOOGLE_AI_API_KEY')
 
# Documents directory — place your .txt business flow files here
DOCUMENTS_DIR = BASE_DIR / 'documents'

ASGI_APPLICATION = 'ANGKORTRANS.asgi.application'

if DEBUG:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels.layers.InMemoryChannelLayer"
        }
    }
else:
    CHANNEL_LAYERS = {
        "default": {
            "BACKEND": "channels_redis.core.RedisChannelLayer",
            "CONFIG": {
                # "hosts": [("127.0.0.1", 6379)],
                "hosts": ["redis://:<password>@<host>:<port>/0"],
            },
        }
    }

OPENSEARCH_DSL = {
    'default': {
        'hosts': 'localhost:9200'
    },
}


# GraphQL
GRAPHENE = {
    'SCHEMA': 'rama_gallery.api.schema.schema'
}

# Celery
CELERY_BROKER_URL = f"redis://{os.getenv('REDIS_HOST', 'localhost')}:{os.getenv('REDIS_PORT', '6379')}/0"
CELERY_RESULT_BACKEND = f"redis://{os.getenv('REDIS_HOST', 'localhost')}:{os.getenv('REDIS_PORT', '6379')}/0"
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'

# Static & Media
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

## If Redis is only used for cache or queue: Temporarily disable Redis (if you just want Django to run)
# ======================
# CACHE CONFIGURATION (Critical for django-ratelimit)
# ======================
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        # 'BACKEND': 'django_redis.cache.RedisCache',
        # 'LOCATION': 'redis://127.0.0.1:6379/1',
        # 'OPTIONS': {
        #     'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        # }
        'LOCATION': 'unique-snowflake',   # Helps a bit, but still not shared
    }
}

# For better rate limiting (Recommended)
# Install django-redis or use database cache in production
# CACHES = {
#     'default': {
#         'BACKEND': 'django_redis.cache.RedisCache',
#         'LOCATION': 'redis://127.0.0.1:6379/1',
#         'OPTIONS': {
#             'CLIENT_CLASS': 'django_redis.client.DefaultClient',
#         }
#     }
# }