"""
Django settings for ANGKORTRANS project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import environ
import os

# # Build paths inside the project like this: BASE_DIR / 'subdir'.
# # BASE_DIR = Path(__file__).resolve().parent.parent

# # Initialize environment variables
env = environ.Env(
    # set casting, default value
    DEBUG=(bool, False)
)
# # Set the project base directory
# # Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
# # Take environment variables from .env file
# # Read .env file
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# # Then use env
DEBUG = env('DEBUG')

SERVER_PORT = env('SERVER_PORT')

# # Quick-start development settings - unsuitable for production
# # See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# # SECURITY WARNING: keep the secret key used in production secret!
# # Raises Django's ImproperlyConfigured
# # exception if SECRET_KEY not in os.environ
SECRET_KEY = env('SECRET_KEY')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=[
    "127.0.0.1",
    "localhost",
    "0.0.0.0",          # useful if you want to access from other devices
    # add your domain / IP here for production
])
# # Optional: make runserver bind to 0.0.0.0 by default in dev
if DEBUG:
    ALLOWED_HOSTS += ["0.0.0.0"]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
SIMPLE_JWT = { #This makes SimpleJWT use: (user.ID) instead of:(user.id)
    'USER_ID_FIELD': 'ID',
    # 'USER_ID_FIELD': 'ID',
    'USER_ID_CLAIM': 'user_id',
}
AUTH_USER_MODEL = 'accounts.Users' #for django auth system, but we are using custom auth with JWT, so we will handle user authentication manually in views and serializers. This allows us to have more control over the user model and authentication process without being tied to Django's built-in auth system. We can still use Django's password hashing utilities for security, but we won't be using the full AbstractBaseUser or PermissionsMixin features.

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

   # your apps...
    'accounts',
    'api_app',
    'inventory',
    'admin_address',

    # DRF + Spectacular
    'rest_framework',          # if you use DRF
    'rest_framework_simplejwt',
    'drf_spectacular',         # ← add here, preferably at the bottom

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'ANGKORTRANS.urls'

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    # 'DEFAULT_PERMISSION_CLASSES': [
    #     "rest_framework.permissions.AllowAny"
    # ],
    # 'DEFAULT_PERMISSION_CLASSES': [
    #     "rest_framework.permissions.IsAuthenticated"
    # ]
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.MultiPartParser',
    ],
}

# Central API Configuration
API_VERSION = '1.0.0'          # ← Change this when you release a new version
APP_TITLE = 'AngkorTrans API'
SPECTACULAR_SETTINGS = {
    'TITLE': APP_TITLE,                    # Correct key is 'TITLE' (not 'APP_TITLE')
    'DESCRIPTION': 'Ancient Powered Neural Translation API - Khmer ↔ English & 100+ languages',
    # 'VERSION': '1.0.0',
    'VERSION': API_VERSION,          # ← This will be used in docs too
    'SERVE_INCLUDE_SCHEMA': False,
    'SWAGGER_UI_DIST': 'https://cdnjs.cloudflare.com/ajax/libs/swagger-ui/5.17.14/',
    'SWAGGER_UI_FAVICON_HREF': 'https://yourdomain.com/static/favicon.ico',  # optional
    # To use custom template:
    'SWAGGER_UI_TEMPLATE': 'drf_spectacular/swagger_ui.html',   # This line enables your custom file
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': True,
        'defaultModelsExpandDepth': 1,
        'docExpansion': 'none',
    },
    'REDOC_SETTINGS': {
        'theme': {
            'primaryColor': '#ff3366',
            'backgroundColor': '#0a0a0a',
        }
    },
}


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': [],
        #  "DIRS": [BASE_DIR / "templates"],  # IMPORTANT
        "DIRS": [os.path.join(BASE_DIR, "templates")],  # ✅ IMPORTANT
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
# CORS Settings - Allow Nuxt dev server
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://localhost:3001",
]
CORS_ALLOW_ALL_ORIGINS = DEBUG
WSGI_APPLICATION = 'ANGKORTRANS.wsgi.application'

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
 
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'
 
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': env('DB_NAME', default='ANGKORTRANS'),
        # 'NAME': 'ANGKORTRANS',           # Main / shared database
        'USER': env('DB_USER', default='root'),
        'PASSWORD': env('DB_PASSWORD', default=''),
        'HOST': env('DB_HOST', default='localhost'),  # or your server IP
        'PORT': env('DB_PORT', default='3306'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            "ssl": {"ssl-mode": "REQUIRED"},
        },
        'CONN_MAX_AGE': 300,             # Keep connection alive a bit longer
        "ATOMIC_REQUESTS": False,   # ✅ explicitly safe
    },
    # # Optional: Add more static client databases (same server, different NAME)
    # 'client1': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'angkortrans_client1',
    #     'USER': 'your_mysql_user',
    #     'PASSWORD': 'your_mysql_password',
    #     'HOST': 'localhost',
    #     'PORT': '3306',
    #     'OPTIONS': {'charset': 'utf8mb4'},
    # },
    # 'client2': {
    #     'ENGINE': 'django.db.backends.mysql',
    #     'NAME': 'angkortrans_client2',
    #     'USER': 'your_mysql_user',
    #     'PASSWORD': 'your_mysql_password',
    #     'HOST': 'localhost',
    #     'PORT': '3306',
    #     'OPTIONS': {'charset': 'utf8mb4'},
    # },
    # Add more static clients here as needed...
}

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
# Optional: Close connections quickly for dynamic use
DATABASE_ROUTERS = []  # You can add custom router if needed

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'


# Google AI Studio API Key
GOOGLE_AI_API_KEY = env('GOOGLE_AI_API_KEY')
 
# Documents directory — place your .txt business flow files here
DOCUMENTS_DIR = BASE_DIR / 'documents'